# Generated by Django 5.2.5 on 2025-08-14 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchticket',
            name='assigned_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game'),
        ),
        migrations.AddField(
            model_name='matchticket',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
