# Generated by Django 5.2.5 on 2025-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_friendinvite_status_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvite',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
