# Generated by Django 5.2.5 on 2025-08-14 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(default='SETUP', max_length=16)),
                ('turn', models.IntegerField(default=1)),
                ('bank_ms_p1', models.IntegerField(default=900000)),
                ('bank_ms_p2', models.IntegerField(default=900000)),
                ('pauses_long_p1', models.IntegerField(default=1)),
                ('pauses_short_p1', models.IntegerField(default=1)),
                ('pauses_long_p2', models.IntegerField(default=1)),
                ('pauses_short_p2', models.IntegerField(default=1)),
                ('setup_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('turn_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('pause_until', models.DateTimeField(blank=True, null=True)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('ready_p1', models.BooleanField(default=False)),
                ('ready_p2', models.BooleanField(default=False)),
                ('ready_at_p1', models.DateTimeField(blank=True, null=True)),
                ('ready_at_p2', models.DateTimeField(blank=True, null=True)),
                ('win_reason', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='KilledCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('piece', models.CharField(max_length=8)),
                ('killed', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('actor', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
            ],
        ),
    ]
