# Generated by Django 5.2.5 on 2025-08-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pause_until',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pauses_long_p1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pauses_long_p2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pauses_short_p1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pauses_short_p2',
        ),
    ]
