# Generated by Django 5.2.5 on 2025-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_pause_until_remove_game_pauses_long_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='long_pause_p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='long_pause_p2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='pause_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='short_pause_p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='short_pause_p2',
            field=models.BooleanField(default=False),
        ),
    ]
