# Generated by Django 5.2.5 on 2025-08-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_long_pause_p1_game_long_pause_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pause_until',
        ),
    ]
