# Generated by Django 5.2.5 on 2025-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_pause_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pause_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
