# Generated by Django 5.2.5 on 2025-08-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_pause_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pause_initiator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
