# Generated by Django 5.2.5 on 2025-08-20 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_pause_initiator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_tick_at',
        ),
        migrations.AddField(
            model_name='game',
            name='turn_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='killedcounter',
            unique_together={('game', 'owner', 'piece')},
        ),
    ]
