# Generated by Django 5.2.5 on 2025-08-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_move_options_remove_game_last_tick_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_bank_update',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
