# Generated by Django 5.2.5 on 2025-08-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_last_bank_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_bank_update_p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_bank_update_p2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_start_time_p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_start_time_p2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
